name: aws

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  validate-fmt:
    name: validate-fmt  
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo GH_Actioning 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -diff
      - name: Terraform Validate
        run: terraform validate
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::373822708689:role/GithubActions-VPCadmin
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          role-session-name: GithubActionsSession
      - name: test aws id
        run: aws sts get-caller-identity
      - name: create test vpc 
        run: aws ec2 create-vpc --cidr-block 10.10.0.0/16