name: ghaction_workflow_aws

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  validate-fmt:
    name: validate-fmt  
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -diff
      - name: Terraform Validate
        run: terraform validate
      - name: environment status
        run: env
  Build:
    needs: [validate-fmt]
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get AWS Credentials for Management Account via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.GH_SECRET_AWS_ROLE }}
          role-duration-seconds: 900 # the ttl of the session, in seconds, minimum=900s=15min 
          role-session-name: GithubActionsSession
          mask-aws-account-id: false
      - name: show credentials
        run: |
              aws sts get-caller-identity
              env | grep AWS > env.txt
              more ~/.aws/credentials > creds.txt
              echo ${{ env.AWS_SESSION_TOKEN }} #>token.txt
      - name: upload files to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: .
      - name: Assume AWS Credentials Target Account 
        uses: aws-actions/configure-aws-credentials@v1
        continue-on-error: true
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          role-to-assume: arn:aws:iam::697627695456:role/OrganizationAccountAccessRole
          role-duration-seconds: 900 # the ttl of the session, in seconds, minimum=900s=15min 
          role-session-name: GithubActionsSession
      - name: show credentials
        run: aws sts get-caller-identity
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -input=false
      #- name: Terraform Plan
      #  run: terraform plan -input=false
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
